server:
  port: 8183

spring:
  application:
    name: jungle-langchain4j-demo

# langchain4j
#langchain4j:
#  open-ai:
#  ollama:
#    chat-model:
#      base-url: http://localhost:11434
#      model-name: llama3.1
